version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: digital_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  library-app:
    image: shivam2303/library-book-management-system:latest
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/digital_library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"

volumes:
  postgres-data:
